export const ErrorCodes = {
  // SYSTEM
  INTERNAL_SERVER_ERROR: 'SYS_001',
  MAINTENANCE_MODE: 'SYS_002',
  TOO_MANY_REQUESTS: 'SYS_003',

  // REQUEST
  VALIDATION_ERROR: 'REQ_001',
  BAD_REQUEST: 'REQ_002',
  PAYLOAD_TOO_LARGE: 'REQ_003',
  UNSUPPORTED_MEDIA_TYPE: 'REQ_004',

  // RESOURCE
  NOT_FOUND: 'RES_001',
  DUPLICATE_ENTRY: 'RES_002',
  CONFLICT: 'RES_003',
  RESOURCE_GONE: 'RES_004',

  // AUTH
  UNAUTHORIZED: 'AUTH_001',
  FORBIDDEN: 'AUTH_002',
  INVALID_TOKEN: 'AUTH_003',
  TOKEN_EXPIRED: 'AUTH_004',
  SESSION_EXPIRED: 'AUTH_005',
  SESSION_REPLACED: 'AUTH_006',
  TOKEN_MISSING: 'AUTH_007',
  OAUTH_STATE_INVALID: 'AUTH_008',
  GOOGLE_EMAIL_NOT_VERIFIED: 'AUTH_009',
  GOOGLE_ACCOUNT_CONFLICT: 'AUTH_010',
  GOOGLE_ACCOUNT_MISMATCH: 'AUTH_011',
  GOOGLE_TOKEN_INVALID: 'AUTH_012',
  TOKEN_REUSED: 'AUTH_013',

  // PERMISSION
  PERMISSION_DENIED: 'PERM_001',
  ROLE_NOT_ALLOWED: 'PERM_002',

  // ACCOUNT
  ACCOUNT_NOT_VERIFIED: 'ACC_001',
  ACCOUNT_LOCKED: 'ACC_002',
  INVALID_CREDENTIALS: 'ACC_003',
  OTP_INVALID: 'ACC_004',
  OTP_EXPIRED: 'ACC_005',

  // BUSINESS
  BUSINESS_RULE_VIOLATION: 'BUS_001',
  OPERATION_NOT_ALLOWED: 'BUS_002',
  INSUFFICIENT_BALANCE: 'BUS_003',

  // EXTERNAL
  EXTERNAL_SERVICE_ERROR: 'EXT_001',
  SERVICE_TIMEOUT: 'EXT_002'
} as const;
